set_property PACKAGE_PIN R2 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W7 [get_ports seg[6]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[6]]
set_property PACKAGE_PIN W6 [get_ports seg[5]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[5]]
set_property PACKAGE_PIN U8 [get_ports seg[4]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[4]]
set_property PACKAGE_PIN V8 [get_ports seg[3]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[3]]
set_property PACKAGE_PIN U5 [get_ports seg[2]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[2]]
set_property PACKAGE_PIN V5 [get_ports seg[1]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[1]]
set_property PACKAGE_PIN U7 [get_ports seg[0]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[0]]
set_property PACKAGE_PIN V7 [get_ports DP]
set_property IOSTANDARD LVCMOS33 [get_ports DP]


set_property PACKAGE_PIN U2 [get_ports anodes[0]]
set_property IOSTANDARD LVCMOS33 [get_ports anodes[0]]
set_property PACKAGE_PIN U4 [get_ports anodes[1]]
set_property IOSTANDARD LVCMOS33 [get_ports anodes[1]]
set_property PACKAGE_PIN V4 [get_ports anodes[2]]
set_property IOSTANDARD LVCMOS33 [get_ports anodes[2]]
set_property PACKAGE_PIN W4 [get_ports anodes[3]]
set_property IOSTANDARD LVCMOS33 [get_ports anodes[3]]

set_property PACKAGE_PIN W19 [get_ports BTNL]
set_property IOSTANDARD LVCMOS33 [get_ports BTNL]
set_property PACKAGE_PIN T17 [get_ports BTNR]
set_property IOSTANDARD LVCMOS33 [get_ports BTNR]
set_property PACKAGE_PIN T18 [get_ports BTNU]
set_property IOSTANDARD LVCMOS33 [get_ports BTNU]
set_property PACKAGE_PIN U17 [get_ports BTND]
set_property IOSTANDARD LVCMOS33 [get_ports BTND]
set_property PACKAGE_PIN U18 [get_ports BTNC]
set_property IOSTANDARD LVCMOS33 [get_ports BTNC]

set_property PACKAGE_PIN U16 [get_ports LD0]
set_property IOSTANDARD LVCMOS33 [get_ports LD0]
set_property PACKAGE_PIN P3 [get_ports LD12]
set_property IOSTANDARD LVCMOS33 [get_ports LD12]
set_property PACKAGE_PIN N3 [get_ports LD13]
set_property IOSTANDARD LVCMOS33 [get_ports LD13]
set_property PACKAGE_PIN P1 [get_ports LD14]
set_property IOSTANDARD LVCMOS33 [get_ports LD14]
set_property PACKAGE_PIN L1 [get_ports LD15]
set_property IOSTANDARD LVCMOS33 [get_ports LD15]

set_property PACKAGE_PIN B16 [get_ports alarm_signal]
set_property IOSTANDARD LVCMOS33 [get_ports alarm_signal]